# Generated by Django 5.2.1 on 2025-06-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulink', '0004_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('accept_notifications', models.BooleanField(default=False)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
