# Generated by Django 5.2.1 on 2025-06-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soulink', '0005_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='accept_notifications',
            new_name='accepted_notifications',
        ),
    ]
