# Generated by Django 5.2.1 on 2025-06-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulink', '0006_rename_accept_notifications_subscriber_accepted_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='accepted_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
