# Generated by Django 5.2.4 on 2025-08-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soulink', '0007_alter_subscriber_accepted_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
